// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SignalChain.Data;

#nullable disable

namespace SignalChain.Migrations
{
    [DbContext(typeof(SignalChainDbContext))]
    [Migration("20260721205431_AddSongsStatusRelationship")]
    partial class AddSongsStatusRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "378c862b-2fee-4d7b-bc54-8eaf4d6950bb",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPHuKi2yd3twxsfhO0FBRBw+HOOnve/2AXxtEIQ3gd+VhZw0XWDhjAaQFuDzxu8RSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6017731d-f6b1-47be-9566-1757fe7e6dda",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "8f7b2e4a-1c3d-4f6e-9a8b-5d2c1e0f3a4b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddde2dce-746d-45fb-8c29-aa837c134b89",
                            Email = "ajohnson@signalchain.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJMKt/QTdaIHjOlSZUqcAbJw/T+bUT2dZXCznUebcQt2cK/kMOp/JPCPN3xK/PEGoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "50b3ccee-a4a3-4d94-b8c9-9194311b0ec2",
                            TwoFactorEnabled = false,
                            UserName = "ajohnson"
                        },
                        new
                        {
                            Id = "2a4c6e8f-3b5d-4a7c-8e9f-1d3c5b7a9e0d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "512d139e-ba8a-4356-bdae-33bb8137bbc1",
                            Email = "rjohnson@signalchain.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKzX5ZcAe4aW1RqLG7d/CQ9olaS39qDI4w87syERtiCP9hyWxwNjPpSkJYIb5nSFgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b9d27e03-ede6-479b-82d6-1ca196ef007c",
                            TwoFactorEnabled = false,
                            UserName = "rjohnson"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SignalChain.Models.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GearTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PurchaseYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GearTypeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Gears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GearTypeId = 1,
                            Model = "Apple MacBook Air 2020 M1",
                            PurchaseYear = "2021",
                            Quantity = 1,
                            SerialNumber = "FVFQHNACQ6L7",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            GearTypeId = 2,
                            Model = "Studio Projects B1 Match Pair lrg dia mics",
                            PurchaseYear = "N/A",
                            Quantity = 1,
                            SerialNumber = "SPB1X9876",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            GearTypeId = 2,
                            Model = "Studio Projects B1 lrg dia microphone",
                            PurchaseYear = "2024",
                            Quantity = 1,
                            SerialNumber = "SPB1X12345",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 4,
                            GearTypeId = 2,
                            Model = "Audix i5 microphone",
                            PurchaseYear = "2024",
                            Quantity = 2,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 5,
                            GearTypeId = 3,
                            Model = "Zildjian K hi-hats pair 14-inch",
                            PurchaseYear = "2003",
                            Quantity = 1,
                            SerialNumber = "Top: JC 24956-097, Bottom: JC 24964-085",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 6,
                            GearTypeId = 3,
                            Model = "Sabian AAX Metal crash 16-inch",
                            PurchaseYear = "2004",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 7,
                            GearTypeId = 3,
                            Model = "Zildjian A Medium-Thin crash 18-inch",
                            PurchaseYear = "2017",
                            Quantity = 1,
                            SerialNumber = "AG85199 061",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 8,
                            GearTypeId = 3,
                            Model = "Zildjian A Medium-Thin crash 19-inch",
                            PurchaseYear = "2005",
                            Quantity = 1,
                            SerialNumber = "JE 43363 006",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 9,
                            GearTypeId = 3,
                            Model = "Zildjian K Custom Medium ride 20-inch",
                            PurchaseYear = "2004",
                            Quantity = 1,
                            SerialNumber = "JB 23527-016",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 10,
                            GearTypeId = 3,
                            Model = "Gretsch Brooklyn 6.5x14 snare GB4164S",
                            PurchaseYear = "2023",
                            Quantity = 1,
                            SerialNumber = "033239",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 11,
                            GearTypeId = 3,
                            Model = "Gretsch Brooklyn Series drums",
                            PurchaseYear = "2024",
                            Quantity = 3,
                            SerialNumber = "021463, 021452, 021467",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 12,
                            GearTypeId = 3,
                            Model = "Fender 1105 SXE acoustic guitar",
                            PurchaseYear = "1996",
                            Quantity = 1,
                            SerialNumber = "9091202",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 13,
                            GearTypeId = 3,
                            Model = "Digital Piano 88-Key Keyboard",
                            PurchaseYear = "2025",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 14,
                            GearTypeId = 3,
                            Model = "Trombone Blessing BTB1488O",
                            PurchaseYear = "2025",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 15,
                            GearTypeId = 3,
                            Model = "Tambourine 8-inch Rock 'N' Roll Hall of Fame",
                            PurchaseYear = "N/A",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 16,
                            GearTypeId = 3,
                            Model = "Tambourine 10-inch Meinl Nino",
                            PurchaseYear = "2005",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 17,
                            GearTypeId = 3,
                            Model = "LP cowbell",
                            PurchaseYear = "2006",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 18,
                            GearTypeId = 4,
                            Model = "Vic Firth SIH3 Isolation headphones",
                            PurchaseYear = "N/A",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 19,
                            GearTypeId = 4,
                            Model = "Sennheiser HD 280 Pro headphones",
                            PurchaseYear = "2025",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 20,
                            GearTypeId = 4,
                            Model = "Sterling MX5 monitor speakers pair",
                            PurchaseYear = "2024",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 21,
                            GearTypeId = 4,
                            Model = "PreSonus Studio 1824c audio interface",
                            PurchaseYear = "2024",
                            Quantity = 1,
                            SerialNumber = "SC4E24090030",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 22,
                            GearTypeId = 5,
                            Model = "On-Stage MS7920B Bass Drum/Boom Combo Mic Stand",
                            PurchaseYear = "2024",
                            Quantity = 3,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 23,
                            GearTypeId = 5,
                            Model = "JamStands JS-MSFB50 Low Profile Boom Mic Stand",
                            PurchaseYear = "2024",
                            Quantity = 2,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 24,
                            GearTypeId = 5,
                            Model = "K&M 21021 Extra Tall Boom Microphone Stand",
                            PurchaseYear = "2024",
                            Quantity = 2,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 25,
                            GearTypeId = 2,
                            Model = "Vocal pop filter",
                            PurchaseYear = "2025",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 26,
                            GearTypeId = 3,
                            Model = "Ludwig Classic Series 1972 14x5 metal snare",
                            PurchaseYear = "N/A",
                            Quantity = 1,
                            SerialNumber = "3019535",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 27,
                            GearTypeId = 3,
                            Model = "Ludwig maple snare 14x6.5",
                            PurchaseYear = "2002",
                            Quantity = 1,
                            SerialNumber = "3390269",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 28,
                            GearTypeId = 3,
                            Model = "LP Vibra-slap",
                            PurchaseYear = "2025",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 29,
                            GearTypeId = 3,
                            Model = "LP Sleigh Bells",
                            PurchaseYear = "N/A",
                            Quantity = 1,
                            SerialNumber = "N/A",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("SignalChain.Models.GearSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GearId")
                        .HasColumnType("integer");

                    b.Property<int>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GearId");

                    b.HasIndex("SongId");

                    b.ToTable("GearSongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GearId = 1,
                            SongId = 1
                        },
                        new
                        {
                            Id = 2,
                            GearId = 2,
                            SongId = 1
                        },
                        new
                        {
                            Id = 3,
                            GearId = 3,
                            SongId = 1
                        },
                        new
                        {
                            Id = 4,
                            GearId = 4,
                            SongId = 1
                        },
                        new
                        {
                            Id = 5,
                            GearId = 5,
                            SongId = 1
                        },
                        new
                        {
                            Id = 6,
                            GearId = 7,
                            SongId = 1
                        },
                        new
                        {
                            Id = 7,
                            GearId = 8,
                            SongId = 1
                        },
                        new
                        {
                            Id = 8,
                            GearId = 9,
                            SongId = 1
                        },
                        new
                        {
                            Id = 9,
                            GearId = 10,
                            SongId = 1
                        },
                        new
                        {
                            Id = 10,
                            GearId = 11,
                            SongId = 1
                        },
                        new
                        {
                            Id = 11,
                            GearId = 15,
                            SongId = 1
                        },
                        new
                        {
                            Id = 12,
                            GearId = 18,
                            SongId = 1
                        },
                        new
                        {
                            Id = 13,
                            GearId = 19,
                            SongId = 1
                        },
                        new
                        {
                            Id = 14,
                            GearId = 20,
                            SongId = 1
                        },
                        new
                        {
                            Id = 15,
                            GearId = 21,
                            SongId = 1
                        },
                        new
                        {
                            Id = 16,
                            GearId = 22,
                            SongId = 1
                        },
                        new
                        {
                            Id = 17,
                            GearId = 23,
                            SongId = 1
                        },
                        new
                        {
                            Id = 18,
                            GearId = 24,
                            SongId = 1
                        },
                        new
                        {
                            Id = 19,
                            GearId = 25,
                            SongId = 1
                        },
                        new
                        {
                            Id = 20,
                            GearId = 1,
                            SongId = 2
                        },
                        new
                        {
                            Id = 21,
                            GearId = 2,
                            SongId = 2
                        },
                        new
                        {
                            Id = 22,
                            GearId = 3,
                            SongId = 2
                        },
                        new
                        {
                            Id = 23,
                            GearId = 4,
                            SongId = 2
                        },
                        new
                        {
                            Id = 24,
                            GearId = 5,
                            SongId = 2
                        },
                        new
                        {
                            Id = 25,
                            GearId = 7,
                            SongId = 2
                        },
                        new
                        {
                            Id = 26,
                            GearId = 8,
                            SongId = 2
                        },
                        new
                        {
                            Id = 27,
                            GearId = 9,
                            SongId = 2
                        },
                        new
                        {
                            Id = 28,
                            GearId = 10,
                            SongId = 2
                        },
                        new
                        {
                            Id = 29,
                            GearId = 11,
                            SongId = 2
                        },
                        new
                        {
                            Id = 30,
                            GearId = 15,
                            SongId = 2
                        },
                        new
                        {
                            Id = 31,
                            GearId = 18,
                            SongId = 2
                        },
                        new
                        {
                            Id = 32,
                            GearId = 20,
                            SongId = 2
                        },
                        new
                        {
                            Id = 33,
                            GearId = 21,
                            SongId = 2
                        },
                        new
                        {
                            Id = 34,
                            GearId = 22,
                            SongId = 2
                        },
                        new
                        {
                            Id = 35,
                            GearId = 23,
                            SongId = 2
                        },
                        new
                        {
                            Id = 36,
                            GearId = 24,
                            SongId = 2
                        },
                        new
                        {
                            Id = 37,
                            GearId = 25,
                            SongId = 2
                        },
                        new
                        {
                            Id = 38,
                            GearId = 29,
                            SongId = 2
                        },
                        new
                        {
                            Id = 39,
                            GearId = 1,
                            SongId = 3
                        },
                        new
                        {
                            Id = 40,
                            GearId = 2,
                            SongId = 3
                        },
                        new
                        {
                            Id = 41,
                            GearId = 3,
                            SongId = 3
                        },
                        new
                        {
                            Id = 42,
                            GearId = 4,
                            SongId = 3
                        },
                        new
                        {
                            Id = 43,
                            GearId = 5,
                            SongId = 3
                        },
                        new
                        {
                            Id = 44,
                            GearId = 7,
                            SongId = 3
                        },
                        new
                        {
                            Id = 45,
                            GearId = 8,
                            SongId = 3
                        },
                        new
                        {
                            Id = 46,
                            GearId = 9,
                            SongId = 3
                        },
                        new
                        {
                            Id = 47,
                            GearId = 10,
                            SongId = 3
                        },
                        new
                        {
                            Id = 49,
                            GearId = 12,
                            SongId = 3
                        },
                        new
                        {
                            Id = 50,
                            GearId = 13,
                            SongId = 3
                        },
                        new
                        {
                            Id = 51,
                            GearId = 14,
                            SongId = 3
                        },
                        new
                        {
                            Id = 52,
                            GearId = 16,
                            SongId = 3
                        },
                        new
                        {
                            Id = 53,
                            GearId = 18,
                            SongId = 3
                        },
                        new
                        {
                            Id = 54,
                            GearId = 19,
                            SongId = 3
                        },
                        new
                        {
                            Id = 55,
                            GearId = 20,
                            SongId = 3
                        },
                        new
                        {
                            Id = 56,
                            GearId = 21,
                            SongId = 3
                        },
                        new
                        {
                            Id = 57,
                            GearId = 22,
                            SongId = 3
                        },
                        new
                        {
                            Id = 58,
                            GearId = 23,
                            SongId = 3
                        },
                        new
                        {
                            Id = 59,
                            GearId = 24,
                            SongId = 3
                        },
                        new
                        {
                            Id = 60,
                            GearId = 25,
                            SongId = 3
                        },
                        new
                        {
                            Id = 61,
                            GearId = 26,
                            SongId = 3
                        },
                        new
                        {
                            Id = 62,
                            GearId = 28,
                            SongId = 3
                        },
                        new
                        {
                            Id = 63,
                            GearId = 29,
                            SongId = 3
                        },
                        new
                        {
                            Id = 64,
                            GearId = 1,
                            SongId = 4
                        },
                        new
                        {
                            Id = 65,
                            GearId = 2,
                            SongId = 4
                        },
                        new
                        {
                            Id = 66,
                            GearId = 3,
                            SongId = 4
                        },
                        new
                        {
                            Id = 67,
                            GearId = 4,
                            SongId = 4
                        },
                        new
                        {
                            Id = 68,
                            GearId = 5,
                            SongId = 4
                        },
                        new
                        {
                            Id = 69,
                            GearId = 7,
                            SongId = 4
                        },
                        new
                        {
                            Id = 70,
                            GearId = 8,
                            SongId = 4
                        },
                        new
                        {
                            Id = 71,
                            GearId = 9,
                            SongId = 4
                        },
                        new
                        {
                            Id = 72,
                            GearId = 10,
                            SongId = 4
                        },
                        new
                        {
                            Id = 73,
                            GearId = 12,
                            SongId = 4
                        },
                        new
                        {
                            Id = 74,
                            GearId = 15,
                            SongId = 4
                        },
                        new
                        {
                            Id = 75,
                            GearId = 17,
                            SongId = 4
                        },
                        new
                        {
                            Id = 76,
                            GearId = 18,
                            SongId = 4
                        },
                        new
                        {
                            Id = 77,
                            GearId = 20,
                            SongId = 4
                        },
                        new
                        {
                            Id = 78,
                            GearId = 21,
                            SongId = 4
                        },
                        new
                        {
                            Id = 79,
                            GearId = 22,
                            SongId = 4
                        },
                        new
                        {
                            Id = 80,
                            GearId = 23,
                            SongId = 4
                        },
                        new
                        {
                            Id = 81,
                            GearId = 24,
                            SongId = 4
                        },
                        new
                        {
                            Id = 82,
                            GearId = 25,
                            SongId = 4
                        },
                        new
                        {
                            Id = 83,
                            GearId = 27,
                            SongId = 4
                        },
                        new
                        {
                            Id = 84,
                            GearId = 28,
                            SongId = 4
                        },
                        new
                        {
                            Id = 85,
                            GearId = 29,
                            SongId = 4
                        },
                        new
                        {
                            Id = 86,
                            GearId = 1,
                            SongId = 5
                        },
                        new
                        {
                            Id = 87,
                            GearId = 2,
                            SongId = 5
                        },
                        new
                        {
                            Id = 88,
                            GearId = 3,
                            SongId = 5
                        },
                        new
                        {
                            Id = 89,
                            GearId = 4,
                            SongId = 5
                        },
                        new
                        {
                            Id = 90,
                            GearId = 5,
                            SongId = 5
                        },
                        new
                        {
                            Id = 91,
                            GearId = 7,
                            SongId = 5
                        },
                        new
                        {
                            Id = 92,
                            GearId = 8,
                            SongId = 5
                        },
                        new
                        {
                            Id = 93,
                            GearId = 9,
                            SongId = 5
                        },
                        new
                        {
                            Id = 94,
                            GearId = 10,
                            SongId = 5
                        },
                        new
                        {
                            Id = 95,
                            GearId = 11,
                            SongId = 5
                        },
                        new
                        {
                            Id = 96,
                            GearId = 15,
                            SongId = 5
                        },
                        new
                        {
                            Id = 97,
                            GearId = 18,
                            SongId = 5
                        },
                        new
                        {
                            Id = 98,
                            GearId = 20,
                            SongId = 5
                        },
                        new
                        {
                            Id = 99,
                            GearId = 21,
                            SongId = 5
                        },
                        new
                        {
                            Id = 100,
                            GearId = 22,
                            SongId = 5
                        },
                        new
                        {
                            Id = 101,
                            GearId = 23,
                            SongId = 5
                        },
                        new
                        {
                            Id = 102,
                            GearId = 24,
                            SongId = 5
                        },
                        new
                        {
                            Id = 103,
                            GearId = 25,
                            SongId = 5
                        },
                        new
                        {
                            Id = 104,
                            GearId = 1,
                            SongId = 6
                        },
                        new
                        {
                            Id = 105,
                            GearId = 2,
                            SongId = 6
                        },
                        new
                        {
                            Id = 106,
                            GearId = 3,
                            SongId = 6
                        },
                        new
                        {
                            Id = 107,
                            GearId = 4,
                            SongId = 6
                        },
                        new
                        {
                            Id = 108,
                            GearId = 5,
                            SongId = 6
                        },
                        new
                        {
                            Id = 109,
                            GearId = 6,
                            SongId = 6
                        },
                        new
                        {
                            Id = 110,
                            GearId = 7,
                            SongId = 6
                        },
                        new
                        {
                            Id = 111,
                            GearId = 9,
                            SongId = 6
                        },
                        new
                        {
                            Id = 112,
                            GearId = 10,
                            SongId = 6
                        },
                        new
                        {
                            Id = 113,
                            GearId = 12,
                            SongId = 6
                        },
                        new
                        {
                            Id = 114,
                            GearId = 13,
                            SongId = 6
                        },
                        new
                        {
                            Id = 115,
                            GearId = 15,
                            SongId = 6
                        },
                        new
                        {
                            Id = 116,
                            GearId = 16,
                            SongId = 6
                        },
                        new
                        {
                            Id = 117,
                            GearId = 18,
                            SongId = 6
                        },
                        new
                        {
                            Id = 118,
                            GearId = 19,
                            SongId = 6
                        },
                        new
                        {
                            Id = 119,
                            GearId = 20,
                            SongId = 6
                        },
                        new
                        {
                            Id = 120,
                            GearId = 21,
                            SongId = 6
                        },
                        new
                        {
                            Id = 121,
                            GearId = 22,
                            SongId = 6
                        },
                        new
                        {
                            Id = 122,
                            GearId = 23,
                            SongId = 6
                        },
                        new
                        {
                            Id = 123,
                            GearId = 24,
                            SongId = 6
                        },
                        new
                        {
                            Id = 124,
                            GearId = 25,
                            SongId = 6
                        },
                        new
                        {
                            Id = 125,
                            GearId = 27,
                            SongId = 6
                        },
                        new
                        {
                            Id = 126,
                            GearId = 1,
                            SongId = 7
                        },
                        new
                        {
                            Id = 127,
                            GearId = 2,
                            SongId = 7
                        },
                        new
                        {
                            Id = 128,
                            GearId = 3,
                            SongId = 7
                        },
                        new
                        {
                            Id = 129,
                            GearId = 4,
                            SongId = 7
                        },
                        new
                        {
                            Id = 130,
                            GearId = 5,
                            SongId = 7
                        },
                        new
                        {
                            Id = 131,
                            GearId = 7,
                            SongId = 7
                        },
                        new
                        {
                            Id = 132,
                            GearId = 8,
                            SongId = 7
                        },
                        new
                        {
                            Id = 133,
                            GearId = 9,
                            SongId = 7
                        },
                        new
                        {
                            Id = 134,
                            GearId = 10,
                            SongId = 7
                        },
                        new
                        {
                            Id = 135,
                            GearId = 11,
                            SongId = 7
                        },
                        new
                        {
                            Id = 136,
                            GearId = 12,
                            SongId = 7
                        },
                        new
                        {
                            Id = 137,
                            GearId = 14,
                            SongId = 7
                        },
                        new
                        {
                            Id = 138,
                            GearId = 15,
                            SongId = 7
                        },
                        new
                        {
                            Id = 139,
                            GearId = 18,
                            SongId = 7
                        },
                        new
                        {
                            Id = 140,
                            GearId = 20,
                            SongId = 7
                        },
                        new
                        {
                            Id = 141,
                            GearId = 21,
                            SongId = 7
                        },
                        new
                        {
                            Id = 142,
                            GearId = 22,
                            SongId = 7
                        },
                        new
                        {
                            Id = 143,
                            GearId = 23,
                            SongId = 7
                        },
                        new
                        {
                            Id = 144,
                            GearId = 24,
                            SongId = 7
                        },
                        new
                        {
                            Id = 145,
                            GearId = 25,
                            SongId = 7
                        },
                        new
                        {
                            Id = 146,
                            GearId = 1,
                            SongId = 8
                        },
                        new
                        {
                            Id = 147,
                            GearId = 2,
                            SongId = 8
                        },
                        new
                        {
                            Id = 148,
                            GearId = 3,
                            SongId = 8
                        },
                        new
                        {
                            Id = 149,
                            GearId = 4,
                            SongId = 8
                        },
                        new
                        {
                            Id = 150,
                            GearId = 5,
                            SongId = 8
                        },
                        new
                        {
                            Id = 151,
                            GearId = 7,
                            SongId = 8
                        },
                        new
                        {
                            Id = 152,
                            GearId = 8,
                            SongId = 8
                        },
                        new
                        {
                            Id = 153,
                            GearId = 9,
                            SongId = 8
                        },
                        new
                        {
                            Id = 154,
                            GearId = 10,
                            SongId = 8
                        },
                        new
                        {
                            Id = 155,
                            GearId = 12,
                            SongId = 8
                        },
                        new
                        {
                            Id = 156,
                            GearId = 13,
                            SongId = 8
                        },
                        new
                        {
                            Id = 157,
                            GearId = 16,
                            SongId = 8
                        },
                        new
                        {
                            Id = 158,
                            GearId = 17,
                            SongId = 8
                        },
                        new
                        {
                            Id = 159,
                            GearId = 18,
                            SongId = 8
                        },
                        new
                        {
                            Id = 160,
                            GearId = 19,
                            SongId = 8
                        },
                        new
                        {
                            Id = 161,
                            GearId = 20,
                            SongId = 8
                        },
                        new
                        {
                            Id = 162,
                            GearId = 21,
                            SongId = 8
                        },
                        new
                        {
                            Id = 163,
                            GearId = 22,
                            SongId = 8
                        },
                        new
                        {
                            Id = 164,
                            GearId = 23,
                            SongId = 8
                        },
                        new
                        {
                            Id = 165,
                            GearId = 24,
                            SongId = 8
                        },
                        new
                        {
                            Id = 166,
                            GearId = 25,
                            SongId = 8
                        },
                        new
                        {
                            Id = 167,
                            GearId = 26,
                            SongId = 8
                        },
                        new
                        {
                            Id = 168,
                            GearId = 1,
                            SongId = 9
                        },
                        new
                        {
                            Id = 169,
                            GearId = 2,
                            SongId = 9
                        },
                        new
                        {
                            Id = 170,
                            GearId = 3,
                            SongId = 9
                        },
                        new
                        {
                            Id = 171,
                            GearId = 4,
                            SongId = 9
                        },
                        new
                        {
                            Id = 172,
                            GearId = 5,
                            SongId = 9
                        },
                        new
                        {
                            Id = 173,
                            GearId = 7,
                            SongId = 9
                        },
                        new
                        {
                            Id = 174,
                            GearId = 8,
                            SongId = 9
                        },
                        new
                        {
                            Id = 175,
                            GearId = 9,
                            SongId = 9
                        },
                        new
                        {
                            Id = 176,
                            GearId = 10,
                            SongId = 9
                        },
                        new
                        {
                            Id = 177,
                            GearId = 11,
                            SongId = 9
                        },
                        new
                        {
                            Id = 178,
                            GearId = 13,
                            SongId = 9
                        },
                        new
                        {
                            Id = 179,
                            GearId = 15,
                            SongId = 9
                        },
                        new
                        {
                            Id = 180,
                            GearId = 17,
                            SongId = 9
                        },
                        new
                        {
                            Id = 181,
                            GearId = 18,
                            SongId = 9
                        },
                        new
                        {
                            Id = 182,
                            GearId = 19,
                            SongId = 9
                        },
                        new
                        {
                            Id = 183,
                            GearId = 20,
                            SongId = 9
                        },
                        new
                        {
                            Id = 184,
                            GearId = 21,
                            SongId = 9
                        },
                        new
                        {
                            Id = 185,
                            GearId = 22,
                            SongId = 9
                        },
                        new
                        {
                            Id = 186,
                            GearId = 23,
                            SongId = 9
                        },
                        new
                        {
                            Id = 187,
                            GearId = 24,
                            SongId = 9
                        },
                        new
                        {
                            Id = 188,
                            GearId = 25,
                            SongId = 9
                        },
                        new
                        {
                            Id = 189,
                            GearId = 28,
                            SongId = 9
                        },
                        new
                        {
                            Id = 190,
                            GearId = 29,
                            SongId = 9
                        });
                });

            modelBuilder.Entity("SignalChain.Models.GearType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GearTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microphone"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Instrument"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Recording"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stands"
                        });
                });

            modelBuilder.Entity("SignalChain.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Writer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearRecorded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Three Hit Combo",
                            StatusId = 2,
                            Title = "Emily",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2026
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Three Hit Combo",
                            StatusId = 4,
                            Title = "Baby Don't Go (It's Christmas)",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Three Hit Combo",
                            StatusId = 4,
                            Title = "Mary Had a Baby (and the Baby Was the Lord)",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Three Hit Combo",
                            StatusId = 4,
                            Title = "Jolly Old St. Nick",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Three Hit Combo",
                            StatusId = 1,
                            Title = "What I Worry",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Three Hit Combo",
                            StatusId = 1,
                            Title = "The Black Hole in the Middle of the Galaxy",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2026
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Three Hit Combo",
                            StatusId = 3,
                            Title = "Morning Fog (Nothing Left to Be)",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2026
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Three Hit Combo",
                            StatusId = 2,
                            Title = "The Grief We've Earned",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Three Hit Combo",
                            StatusId = 3,
                            Title = "Rewasher",
                            UserProfileId = 1,
                            Writer = "Josh Tinley",
                            YearRecorded = 2025
                        });
                });

            modelBuilder.Entity("SignalChain.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Recording"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mixing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mastering"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Released"
                        });
                });

            modelBuilder.Entity("SignalChain.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            Email = "admina@strator.comx",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Strator",
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Address = "202 Oak Avenue",
                            Email = "ajohnson@signalchain.comx",
                            FirstName = "Andre",
                            IdentityUserId = "8f7b2e4a-1c3d-4f6e-9a8b-5d2c1e0f3a4b",
                            LastName = "Johnson",
                            UserName = "ajohnson"
                        },
                        new
                        {
                            Id = 3,
                            Address = "202 Oak Avenue",
                            Email = "rjohnson@signalchain.comx",
                            FirstName = "Rainbow",
                            IdentityUserId = "2a4c6e8f-3b5d-4a7c-8e9f-1d3c5b7a9e0d",
                            LastName = "Johnson",
                            UserName = "rjohnson"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalChain.Models.Gear", b =>
                {
                    b.HasOne("SignalChain.Models.GearType", "GearType")
                        .WithMany()
                        .HasForeignKey("GearTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalChain.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GearType");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SignalChain.Models.GearSong", b =>
                {
                    b.HasOne("SignalChain.Models.Gear", "Gear")
                        .WithMany("GearSongs")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalChain.Models.Song", "Song")
                        .WithMany("GearSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SignalChain.Models.Song", b =>
                {
                    b.HasOne("SignalChain.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SignalChain.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SignalChain.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("SignalChain.Models.Gear", b =>
                {
                    b.Navigation("GearSongs");
                });

            modelBuilder.Entity("SignalChain.Models.Song", b =>
                {
                    b.Navigation("GearSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
